project_id = "jsupvprudyxyiyxwqxuq"

[functions.sync-external-supabase]
verify_jwt = false
[functions.send-registration-code]
verify_jwt = false

[functions.verify-registration-code]
verify_jwt = false

[functions.mark-code-used]
verify_jwt = false